In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/workspaces/MLZoomCamp/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
#creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a=np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]=10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [10]:
#multidimensional arrays
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

In [12]:
n[2]=[1,1,1]

In [13]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [14]:
n[:,1]=[20,10,11]

In [15]:
n

array([[ 1, 20,  3],
       [ 4, 10,  6],
       [ 1, 11,  1]])

In [16]:
#randomly generated arrays
np.random.seed(10)
np.random.rand(5,2,2)

array([[[0.77132064, 0.02075195],
        [0.63364823, 0.74880388]],

       [[0.49850701, 0.22479665],
        [0.19806286, 0.76053071]],

       [[0.16911084, 0.08833981],
        [0.68535982, 0.95339335]],

       [[0.00394827, 0.51219226],
        [0.81262096, 0.61252607]],

       [[0.72175532, 0.29187607],
        [0.91777412, 0.71457578]]])

In [17]:
np.random.randint(low=0, high=100, size=(5,2))

array([[13, 25],
       [13, 92],
       [86, 30],
       [30, 89],
       [12, 65]])

In [18]:
#Element-wise operations
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
a+1

array([1, 2, 3, 4, 5, 6])

In [20]:
a*2

array([ 0,  2,  4,  6,  8, 10])

In [21]:
b=(10+(a*2)**2 )/100
b

array([0.1 , 0.14, 0.26, 0.46, 0.74, 1.1 ])

In [22]:
a+b

array([0.1 , 1.14, 2.26, 3.46, 4.74, 6.1 ])

In [23]:
#comparison operations
a

array([0, 1, 2, 3, 4, 5])

In [24]:
a>=2

array([False, False,  True,  True,  True,  True])

In [25]:
b

array([0.1 , 0.14, 0.26, 0.46, 0.74, 1.1 ])

In [26]:
a>b

array([False,  True,  True,  True,  True,  True])

In [27]:
a[a>b]

array([1, 2, 3, 4, 5])

In [28]:
#summarizing operations
a

array([0, 1, 2, 3, 4, 5])

In [29]:
a.sum()

np.int64(15)

In [30]:
a.std()

np.float64(1.707825127659933)

In [31]:
a.min()

np.int64(0)