# Algebra refresher

In [5]:
import numpy as np

#vector operations
u = np.array([2,4,5,6])

In [6]:
2*u

array([ 4,  8, 10, 12])

In [7]:
v = np.array([1,0,0,2])

In [9]:
u+v

array([3, 4, 5, 8])

In [10]:
u*v

array([ 2,  0,  0, 12])

In [11]:
#multiplication
#dot product

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n= u.shape[0]
    result =0.0
    for i in range(n):
        result = result + u[i]*v[i]
    return result

In [12]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [15]:
U = np.array([
        [2,4,5,6],
        [1,2,1,2],
        [3,1,2,1],
        ])

In [31]:
#matrix-vector multiplication
def matrix_vector_multiplication(U,v):
    assert U.shape[1]==v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result



In [32]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [33]:
#Now with just a function:
U.dot(v)

array([14,  5,  5])

In [34]:
#matrix-matrix multiplication
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:,i] = Uvi
    return result
    


In [35]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
    ])

In [36]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [37]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [42]:
#identity matrix
I = np.eye(3)

In [43]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [59]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [63]:
#Inverse
Vs =V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [66]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [67]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])